from app import fake
from app.settings import STATICFILES_DIRS
import json


"""
Fake models generated by faker...
"""


def generate_events(num):
    events = []

    for i in range(num):
        events.append({
            'date': fake.dateTimeBetween('now', '+1y'),
            'city': fake.city(),
            'state': fake.stateAbbr(),
            'description': fake.text()
        })

    events.sort(key=lambda x: x['date'])

    return events


def get_discography():
    with open(STATICFILES_DIRS[0] + '/albums/discography.json') as f:
        return json.load(f)


events = generate_events(10)
discography = get_discography()
