from app import fake
from app.settings import STATICFILES_DIRS
import json


"""
Fake models generated by faker...
"""

def generate_events(num):
    events = []

    for i in range(num):
        events.append({
            'date': fake.dateTimeBetween('now','+1y'),
            'city': fake.city(),
            'state': fake.stateAbbr(),
            'description': fake.text()
        })

    events.sort(key=lambda x: x['date'])

    return events


def generate_members(num=5):
    members = []

    for i in range(num):
        members.append({
            'name': fake.name(),
            'state': fake.stateAbbr(),
            'bio': fake.text()
        })
    return members

def get_discography():
    with open(STATICFILES_DIRS[0]+'/albums/discography.json') as f:
        return json.load(f)

events = generate_events(10)
members = generate_members()
discography = get_discography()
